"""Add manufacture_year to appliances

Revision ID: 027ad2f422c2
Revises: ce9be0d341f4
Create Date: 2026-08-28 17:53:23.778120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027ad2f422c2'
down_revision = 'ce9be0d341f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacture_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliances', schema=None) as batch_op:
        batch_op.drop_column('manufacture_year')

    # ### end Alembic commands ###
