"""add zones and service category

Revision ID: 1209ac38349f
Revises: 027ad2f422c2
Create Date: 2026-09-01 18:00:54.159554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1209ac38349f'
down_revision = '027ad2f422c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column(
            'category', sa.Enum('maintenance', 'improvement', name='servicecategory', native_enum=False),
            nullable=False, server_default='maintenance',
        ))
        batch_op.create_foreign_key(
            'fk_service_records_zone_id_zones', 'zones', ['zone_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_service_records_zone_id_zones', type_='foreignkey')
        batch_op.drop_column('category')
        batch_op.drop_column('zone_id')

    op.drop_table('zones')
    # ### end Alembic commands ###
