"""add rating to vendors

Revision ID: 189340db6d20
Revises: 1209ac38349f
Create Date: 2026-09-02 21:06:35.076362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189340db6d20'
down_revision = '1209ac38349f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.create_check_constraint('ck_vendor_rating_range', 'rating IS NULL OR rating BETWEEN 1 AND 5')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint('ck_vendor_rating_range', type_='check')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
