"""add paint colors

Revision ID: 48801cdbd3fc
Revises: 3bfdedad2d65
Create Date: 2026-08-28 15:47:39.143577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48801cdbd3fc'
down_revision = '3bfdedad2d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paint_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('color_name', sa.String(length=120), nullable=True),
    sa.Column('color_code', sa.String(length=80), nullable=True),
    sa.Column('hex_color', sa.String(length=7), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_links', schema=None) as batch_op:
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('appliance', 'home', 'vendor', 'paint_color', name='documententitytype', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_links', schema=None) as batch_op:
        batch_op.alter_column('entity_type',
               existing_type=sa.Enum('appliance', 'home', 'vendor', 'paint_color', name='documententitytype', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    op.drop_table('paint_colors')
    # ### end Alembic commands ###
