"""add feature requests

Revision ID: 58e4c601ed3e
Revises: df4176c78ad2
Create Date: 2026-10-05 17:28:18.450039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e4c601ed3e'
down_revision = 'df4176c78ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('request_type', sa.String(length=40), nullable=False),
    sa.Column('area', sa.String(length=40), nullable=False),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('trying_to_do', sa.Text(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('workaround', sa.Text(), nullable=True),
    sa.Column('proposed_behavior', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=False),
    sa.Column('data_entities', sa.Text(), nullable=True),
    sa.Column('implementation_notes', sa.Text(), nullable=True),
    sa.Column('out_of_scope', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('priority_reason', sa.String(length=300), nullable=True),
    sa.Column('related_requests', sa.String(length=200), nullable=True),
    sa.Column('submitted_by', sa.String(length=120), nullable=False),
    sa.Column('context_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('unread', 'approved', 'denied', 'implemented', name='featurerequeststatus', native_enum=False), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_requests')
    # ### end Alembic commands ###
