"""Add rooms and multi-location paint colors

Revision ID: 935abfdda254
Revises: 48801cdbd3fc
Create Date: 2026-08-28 17:33:28.836751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935abfdda254'
down_revision = '48801cdbd3fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('floor', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appliances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_appliances_room_id_rooms', 'rooms', ['room_id'], ['id'])

    with op.batch_alter_table('paint_colors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_paint_colors_room_id_rooms', 'rooms', ['room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paint_colors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_paint_colors_room_id_rooms', type_='foreignkey')
        batch_op.alter_column('location',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('room_id')

    with op.batch_alter_table('appliances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appliances_room_id_rooms', type_='foreignkey')
        batch_op.drop_column('room_id')

    op.drop_table('rooms')
    # ### end Alembic commands ###
