"""add zone maintenance tasks and pro service interval

Revision ID: b80e93ec1331
Revises: fac1697a0548
Create Date: 2026-09-03 13:54:28.197703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80e93ec1331'
down_revision = 'fac1697a0548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_id', sa.Integer(), nullable=True))
        batch_op.alter_column('appliance_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_maintenance_tasks_zone_id_zones', 'zones', ['zone_id'], ['id'])
        batch_op.create_check_constraint('ck_maintenance_task_appliance_xor_zone', '(appliance_id IS NOT NULL AND zone_id IS NULL) OR (appliance_id IS NULL AND zone_id IS NOT NULL)')

    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pro_service_interval_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pro_service_interval_unit', sa.Enum('days', 'weeks', 'months', 'years', name='frequencyunit', native_enum=False), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_column('pro_service_interval_unit')
        batch_op.drop_column('pro_service_interval_value')

    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('ck_maintenance_task_appliance_xor_zone', type_='check')
        batch_op.drop_constraint('fk_maintenance_tasks_zone_id_zones', type_='foreignkey')
        batch_op.alter_column('appliance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('zone_id')

    # ### end Alembic commands ###
