"""add spec fields to appliances

Revision ID: ca4fb53427d2
Revises: eff0d1a0689d
Create Date: 2026-10-05 20:37:37.485325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4fb53427d2'
down_revision = 'eff0d1a0689d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('electrical_specs', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('dimensions', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliances', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('dimensions')
        batch_op.drop_column('electrical_specs')
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
