"""Add primary photo support to document links

Revision ID: ce9be0d341f4
Revises: 935abfdda254
Create Date: 2026-08-28 17:48:08.235826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9be0d341f4'
down_revision = '935abfdda254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_links', schema=None) as batch_op:
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
