"""add service_record document links

Revision ID: df4176c78ad2
Revises: b80e93ec1331
Create Date: 2026-09-04 11:24:03.752045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4176c78ad2'
down_revision = 'b80e93ec1331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_links', schema=None) as batch_op:
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('appliance', 'home', 'vendor', 'paint_color', 'service_record', name='documententitytype', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_links', schema=None) as batch_op:
        batch_op.alter_column('entity_type',
               existing_type=sa.Enum('appliance', 'home', 'vendor', 'paint_color', 'service_record', name='documententitytype', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
