"""initial schema

Revision ID: eaa7c58619a6
Revises: 
Create Date: 2026-08-27 05:31:29.190028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa7c58619a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('maintenance', 'consumable', name='templatekind', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency_value', sa.Integer(), nullable=True),
    sa.Column('frequency_unit', sa.Enum('days', 'weeks', 'months', 'years', name='frequencyunit', native_enum=False), nullable=True),
    sa.Column('part_number_hint', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_templates_category'), ['category'], unique=False)

    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'key', name='uq_app_setting_household_key')
    )
    op.create_table('appliances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('make', sa.String(length=120), nullable=True),
    sa.Column('model_number', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='appliancestatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pro_service_interval_value', sa.Integer(), nullable=True),
    sa.Column('pro_service_interval_unit', sa.Enum('days', 'weeks', 'months', 'years', name='frequencyunit', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('consumables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('part_number', sa.String(length=120), nullable=True),
    sa.Column('purchase_url', sa.String(length=1000), nullable=True),
    sa.Column('frequency_value', sa.Integer(), nullable=True),
    sa.Column('frequency_unit', sa.Enum('days', 'weeks', 'months', 'years', name='frequencyunit', native_enum=False), nullable=True),
    sa.Column('last_replaced_at', sa.Date(), nullable=True),
    sa.Column('next_due_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('photo', 'manual', 'receipt', 'other', name='documenttype', native_enum=False), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(file_path IS NOT NULL AND external_url IS NULL) OR (file_path IS NULL AND external_url IS NOT NULL)', name='ck_document_file_xor_url'),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency_value', sa.Integer(), nullable=False),
    sa.Column('frequency_unit', sa.Enum('days', 'weeks', 'months', 'years', name='frequencyunit', native_enum=False), nullable=False),
    sa.Column('last_completed_at', sa.Date(), nullable=True),
    sa.Column('next_due_at', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.Date(), nullable=False),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_logs')
    op.drop_table('service_records')
    op.drop_table('maintenance_tasks')
    op.drop_table('documents')
    op.drop_table('consumables')
    op.drop_table('users')
    op.drop_table('appliances')
    op.drop_table('app_settings')
    op.drop_table('households')
    with op.batch_alter_table('category_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_templates_category'))

    op.drop_table('category_templates')
    # ### end Alembic commands ###
