"""add vendor quotes

Revision ID: eff0d1a0689d
Revises: 58e4c601ed3e
Create Date: 2026-10-05 17:46:06.109546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff0d1a0689d'
down_revision = '58e4c601ed3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='quotestatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_quotes_vendor_id'), ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_quotes_vendor_id'))

    op.drop_table('vendor_quotes')
    # ### end Alembic commands ###
